
language: python

python:
  - "2.7"

cache: pip

# Command to install HappyML and dependencies.
install:
  - python setup.py install

# Command to run tests
script:
  - python setup.py nosetests --with-coverage --cover-package=happyml

# Upload coverage results.
after_success:
  - /home/travis/virtualenv/python2.7.9/bin/coveralls
