
language: python

python:
  - "2.7"

cache: pip

# Command to install HappyML and dependencies.
install:
  - pip install coveralls
  - python setup.py install

# Command to run tests
script:
  - python setup.py nosetests --with-coverage --cover-package=happyml

# Upload coverage results.
# COVERALLS_REPO_TOKEN env var should be defined.
after_success:
  - coveralls
