
language: python

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"

# Command to install HappyML and dependencies.
install:
  - sudo python setup.py install

# Command to run tests
script:
  - python setup.py test
